// Auto-generated by build-sitemap.py — edits will be overwritten
window.__SITEMAP__ = {
  "files": [
    ".nojekyll",
    "404.html",
    "about.html",
    "all-images.html",
    "blog.html",
    "favicon.ico",
    "galleries.html",
    "guestbook.html",
    "index.html",
    "plants.html",
    "README.md",
    "robots.txt",
    "sitemap.html"
  ],
  "folders": {
    "blog": {
      "files": [
        "2015-06-16-e-mail-to-myself-2015.html",
        "2021-04-28-final-project-for-fintech-2021.html",
        "2021-09-02-five-essays-from-phil1000.html",
        "2023-08-04-fiction-airplane.html",
        "2024-12-31-m-c-t.html",
        "2025-03-27-nature-being-paradoxical.html",
        "2025-05-15-review-nausea-plus-other.html",
        "2025-06-04-regeneration.html",
        "2025-08-28-a-scruple-scruples.html",
        "2025-09-05-perpetuity.html",
        "2025-09-07-300.html",
        "2025-09-12-what-the-labubu.html",
        "2025-09-30-gap.html",
        "2025-10-17-some-rambling-thoughts-on-ai.html",
        "2025-11-09-please-for-the-love-of-god-slow-down-and-run-them-offline.html",
        "2025-12-01-aoip.html",
        "2026-03-29-untitled.html",
        "2026-04-23-field-notes-march-30-april-8.html",
        "now.html"
      ],
      "folders": {
        "builds": {
          "files": [
            "benchmarks.html",
            "index.html",
            "ipod.html",
            "linux-box-2014.html",
            "lumen-acre.html",
            "mac-pro-2013.html",
            "macbook-air-2014.html",
            "macbook-pro-2012.html",
            "macbook-pro-2021.html",
            "macbook-pro-2021b.html",
            "macbook-pro-2026.html",
            "media-servers.html",
            "misc-plus.html",
            "mycelium.html",
            "neocities-tcwishes.html",
            "raspi3.html",
            "this-site.html",
            "whisker.html"
          ],
          "folders": {}
        }
      }
    },
    "galleries": {
      "files": [
        "animals.html",
        "videos.html"
      ],
      "folders": {
        "cameras": {
          "files": [
            "canon-2022.html",
            "canon-2023.html",
            "canon-2024.html",
            "canon-2025.html",
            "canon-2026.html",
            "canon-elan-ii-2025-2026.html",
            "canon-elan-ii-unknown.html",
            "canon-elan-ii.html",
            "canon-sd400.html",
            "disposable.html",
            "vivitar-big-sur.html",
            "vivitar-il-ne-mo-ut.html",
            "vivitar-pz3090.html",
            "vivitar-san-diego.html",
            "vivitar-utah.html"
          ],
          "folders": {}
        },
        "monthly": {
          "files": [
            "2025-01-jan.html",
            "2025-02-feb.html",
            "2025-03-mar.html",
            "2025-04-apr.html",
            "2025-05-may.html",
            "2025-06-jun.html",
            "2025-07-jul.html",
            "2025-08-aug.html",
            "2025-09-sep.html",
            "2025-10-oct.html",
            "2025-11-nov.html",
            "2025-12-dec.html",
            "2026-01-jan.html",
            "2026-02-feb.html",
            "2026-03-mar.html",
            "2026-04-apr.html",
            "2026-05-appalachia.html",
            "2026-05-chicago.html",
            "2026-05-east-coast.html",
            "2026-05-great-lakes-ohio.html",
            "2026-05-may.html",
            "2026-05-pre-trip.html",
            "2026-05-return.html",
            "2026-06-june.html"
          ],
          "folders": {}
        }
      }
    },
    "images": {
      "files": [
        "10-4.jpg",
        "oneko.gif",
        "silly.jpg",
        "water.gif",
        "animals/",
        "badges/",
        "benchmarking/",
        "blog/",
        "builds/",
        "cameras/",
        "galleries/",
        "monthly/",
        "plants/"
      ],
      "note": "(image directory)"
    },
    "js": {
      "files": [
        "all-images-data.js",
        "blog-nav.js",
        "bot-blocker.js",
        "counter.js",
        "gallery-data.js",
        "gallery.js",
        "image-canvas.js",
        "include.js",
        "oneko.js",
        "sitemap-data.js"
      ],
      "folders": {}
    },
    "plants": {
      "files": [
        "collection.html"
      ],
      "folders": {
        "progress": {
          "files": [
            "2026-01.html",
            "2026-02.html",
            "2026-03.html",
            "2026-04.html",
            "2026-05.html",
            "2026-06.html"
          ],
          "folders": {}
        }
      }
    },
    "styles": {
      "files": [
        "style.css"
      ],
      "folders": {}
    }
  }
};
